version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/e2e-fixture-a"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/e2e-fixture-b"
    schedule:
      interval: "daily"
